In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv("measure of birth and death.csv")
df

,index,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,LBW,LBW_Ind,Min_LBW,...,CI_Min_Suicide,CI_Max_Suicide,Injury,Min_Injury,Max_Injury,CI_Min_Injury,CI_Max_Injury,Total_Births,Total_Deaths,MOBD_Time_Span
0,0,1,1,Autauga,Alabama,AL,29,8.1,4,6.0,...,11.7,23.0,23.0,16.4,27.9,16.9,30.7,3048.0,1867.0,1999-2003
1,1,1,3,Baldwin,Alabama,AL,16,8.6,4,6.3,...,11.0,18.2,30.1,15.6,29.1,25.1,35.1,5471.0,4388.0,2001-2003
2,2,1,5,Barbour,Alabama,AL,51,11.0,4,6.7,...,5.7,16.9,29.6,17.5,35.2,21.5,39.7,1835.0,1538.0,1999-2003
3,3,1,7,Bibb,Alabama,AL,42,8.7,4,5.1,...,9.9,21.3,30.0,20.4,38.1,22.7,38.8,2801.0,2012.0,1994-2003
4,4,1,9,Blount,Alabama,AL,28,7.6,4,5.2,...,10.1,19.8,24.4,16.4,32.6,18.7,31.2,3318.0,2453.0,1999-2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,3136,56,37,Sweetwater,Wyoming,WY,77,8.8,4,5.6,...,20.4,37.3,29.5,22.9,45.3,21.3,39.7,2756.0,1264.0,1999-2003
3137,3137,56,39,Teton,Wyoming,WY,78,8.0,4,3.1,...,7.6,21.0,26.9,5.8,62.9,18.4,37.9,1931.0,680.0,1994-2003
3138,3138,56,41,Uinta,Wyoming,WY,38,11.4,4,5.5,...,12.5,26.1,25.5,15.2,27.5,17.3,36.3,3186.0,1060.0,1994-2003
3139,3139,56,43,Washakie,Wyoming,WY,82,7.3,4,2.5,...,7.2,24.7,33.3,10.8,35.7,22.1,48.1,974.0,844.0,1994-2003
3140,3140,56,45,Weston,Wyoming,WY,78,8.8,4,3.1,...,7.5,29.3,22.6,5.8,62.9,12.8,36.9,670.0,629.0,1994-2003

In [18]:
# Deleting columns
columns_to_remove=['CI_Min_Injury',	'CI_Max_Injury']
df=df.drop(columns=columns_to_remove)
df

,index,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,LBW,LBW_Ind,Min_LBW,...,Min_Suicide,Max_Suicide,CI_Min_Suicide,CI_Max_Suicide,Injury,Min_Injury,Max_Injury,Total_Births,Total_Deaths,MOBD_Time_Span
0,0,1,1,Autauga,Alabama,AL,29,8.1,4,6.0,...,6.7,14.5,11.7,23.0,23.0,16.4,27.9,3048.0,1867.0,1999-2003
1,1,1,3,Baldwin,Alabama,AL,16,8.6,4,6.3,...,7.7,16.0,11.0,18.2,30.1,15.6,29.1,5471.0,4388.0,2001-2003
2,2,1,5,Barbour,Alabama,AL,51,11.0,4,6.7,...,6.1,17.6,5.7,16.9,29.6,17.5,35.2,1835.0,1538.0,1999-2003
3,3,1,7,Bibb,Alabama,AL,42,8.7,4,5.1,...,8.5,21.6,9.9,21.3,30.0,20.4,38.1,2801.0,2012.0,1994-2003
4,4,1,9,Blount,Alabama,AL,28,7.6,4,5.2,...,8.5,17.7,10.1,19.8,24.4,16.4,32.6,3318.0,2453.0,1999-2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,3136,56,37,Sweetwater,Wyoming,WY,77,8.8,4,5.6,...,13.6,28.1,20.4,37.3,29.5,22.9,45.3,2756.0,1264.0,1999-2003
3137,3137,56,39,Teton,Wyoming,WY,78,8.0,4,3.1,...,0.0,29.5,7.6,21.0,26.9,5.8,62.9,1931.0,680.0,1994-2003
3138,3138,56,41,Uinta,Wyoming,WY,38,11.4,4,5.5,...,7.5,20.3,12.5,26.1,25.5,15.2,27.5,3186.0,1060.0,1994-2003
3139,3139,56,43,Washakie,Wyoming,WY,82,7.3,4,2.5,...,6.1,26.4,7.2,24.7,33.3,10.8,35.7,974.0,844.0,1994-2003
3140,3140,56,45,Weston,Wyoming,WY,78,8.8,4,3.1,...,0.0,29.5,7.5,29.3,22.6,5.8,62.9,670.0,629.0,1994-2003

In [19]:
df.dtypes

index                 int64
State_FIPS_Code       int64
County_FIPS_Code      int64
CHSI_County_Name     object
CHSI_State_Name      object
                     ...
Min_Injury          float64
Max_Injury          float64
Total_Births        float64
Total_Deaths        float64
MOBD_Time_Span       object
Length: 67, dtype: object

In [20]:
# Data Types Transformation
df['Min_Injury']=df['Min_Injury'].round(0).astype(int)
df['Max_Injury']=df['Max_Injury'].round(0).astype(int)
df['Total_Births']=df['Total_Births'].round(0).astype(int)
df

,index,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,LBW,LBW_Ind,Min_LBW,...,Min_Suicide,Max_Suicide,CI_Min_Suicide,CI_Max_Suicide,Injury,Min_Injury,Max_Injury,Total_Births,Total_Deaths,MOBD_Time_Span
0,0,1,1,Autauga,Alabama,AL,29,8.1,4,6.0,...,6.7,14.5,11.7,23.0,23.0,16,28,3048,1867.0,1999-2003
1,1,1,3,Baldwin,Alabama,AL,16,8.6,4,6.3,...,7.7,16.0,11.0,18.2,30.1,16,29,5471,4388.0,2001-2003
2,2,1,5,Barbour,Alabama,AL,51,11.0,4,6.7,...,6.1,17.6,5.7,16.9,29.6,18,35,1835,1538.0,1999-2003
3,3,1,7,Bibb,Alabama,AL,42,8.7,4,5.1,...,8.5,21.6,9.9,21.3,30.0,20,38,2801,2012.0,1994-2003
4,4,1,9,Blount,Alabama,AL,28,7.6,4,5.2,...,8.5,17.7,10.1,19.8,24.4,16,33,3318,2453.0,1999-2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,3136,56,37,Sweetwater,Wyoming,WY,77,8.8,4,5.6,...,13.6,28.1,20.4,37.3,29.5,23,45,2756,1264.0,1999-2003
3137,3137,56,39,Teton,Wyoming,WY,78,8.0,4,3.1,...,0.0,29.5,7.6,21.0,26.9,6,63,1931,680.0,1994-2003
3138,3138,56,41,Uinta,Wyoming,WY,38,11.4,4,5.5,...,7.5,20.3,12.5,26.1,25.5,15,28,3186,1060.0,1994-2003
3139,3139,56,43,Washakie,Wyoming,WY,82,7.3,4,2.5,...,6.1,26.4,7.2,24.7,33.3,11,36,974,844.0,1994-2003
3140,3140,56,45,Weston,Wyoming,WY,78,8.8,4,3.1,...,0.0,29.5,7.5,29.3,22.6,6,63,670,629.0,1994-2003

In [21]:
df.dtypes

index                 int64
State_FIPS_Code       int64
County_FIPS_Code      int64
CHSI_County_Name     object
CHSI_State_Name      object
                     ...
Min_Injury            int64
Max_Injury            int64
Total_Births          int64
Total_Deaths        float64
MOBD_Time_Span       object
Length: 67, dtype: object

In [22]:
# Replacing the negative values with NaN
df[df['Suicide']<0]=np.nan
df[df['CI_Min_Suicide']<0]=np.nan
df[df['CI_Max_Suicide']<0]=np.nan
df

,index,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,LBW,LBW_Ind,Min_LBW,...,Min_Suicide,Max_Suicide,CI_Min_Suicide,CI_Max_Suicide,Injury,Min_Injury,Max_Injury,Total_Births,Total_Deaths,MOBD_Time_Span
0,0.0,1.0,1.0,Autauga,Alabama,AL,29.0,8.1,4.0,6.0,...,6.7,14.5,11.7,23.0,23.0,16.0,28.0,3048.0,1867.0,1999-2003
1,1.0,1.0,3.0,Baldwin,Alabama,AL,16.0,8.6,4.0,6.3,...,7.7,16.0,11.0,18.2,30.1,16.0,29.0,5471.0,4388.0,2001-2003
2,2.0,1.0,5.0,Barbour,Alabama,AL,51.0,11.0,4.0,6.7,...,6.1,17.6,5.7,16.9,29.6,18.0,35.0,1835.0,1538.0,1999-2003
3,3.0,1.0,7.0,Bibb,Alabama,AL,42.0,8.7,4.0,5.1,...,8.5,21.6,9.9,21.3,30.0,20.0,38.0,2801.0,2012.0,1994-2003
4,4.0,1.0,9.0,Blount,Alabama,AL,28.0,7.6,4.0,5.2,...,8.5,17.7,10.1,19.8,24.4,16.0,33.0,3318.0,2453.0,1999-2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,3136.0,56.0,37.0,Sweetwater,Wyoming,WY,77.0,8.8,4.0,5.6,...,13.6,28.1,20.4,37.3,29.5,23.0,45.0,2756.0,1264.0,1999-2003
3137,3137.0,56.0,39.0,Teton,Wyoming,WY,78.0,8.0,4.0,3.1,...,0.0,29.5,7.6,21.0,26.9,6.0,63.0,1931.0,680.0,1994-2003
3138,3138.0,56.0,41.0,Uinta,Wyoming,WY,38.0,11.4,4.0,5.5,...,7.5,20.3,12.5,26.1,25.5,15.0,28.0,3186.0,1060.0,1994-2003
3139,3139.0,56.0,43.0,Washakie,Wyoming,WY,82.0,7.3,4.0,2.5,...,6.1,26.4,7.2,24.7,33.3,11.0,36.0,974.0,844.0,1994-2003
3140,3140.0,56.0,45.0,Weston,Wyoming,WY,78.0,8.8,4.0,3.1,...,0.0,29.5,7.5,29.3,22.6,6.0,63.0,670.0,629.0,1994-2003

In [23]:
#  Handling NULL or Infinite Values
df=df.fillna('-')
df

,index,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,LBW,LBW_Ind,Min_LBW,...,Min_Suicide,Max_Suicide,CI_Min_Suicide,CI_Max_Suicide,Injury,Min_Injury,Max_Injury,Total_Births,Total_Deaths,MOBD_Time_Span
0,0.0,1.0,1.0,Autauga,Alabama,AL,29.0,8.1,4.0,6.0,...,6.7,14.5,11.7,23.0,23.0,16.0,28.0,3048.0,1867.0,1999-2003
1,1.0,1.0,3.0,Baldwin,Alabama,AL,16.0,8.6,4.0,6.3,...,7.7,16.0,11.0,18.2,30.1,16.0,29.0,5471.0,4388.0,2001-2003
2,2.0,1.0,5.0,Barbour,Alabama,AL,51.0,11.0,4.0,6.7,...,6.1,17.6,5.7,16.9,29.6,18.0,35.0,1835.0,1538.0,1999-2003
3,3.0,1.0,7.0,Bibb,Alabama,AL,42.0,8.7,4.0,5.1,...,8.5,21.6,9.9,21.3,30.0,20.0,38.0,2801.0,2012.0,1994-2003
4,4.0,1.0,9.0,Blount,Alabama,AL,28.0,7.6,4.0,5.2,...,8.5,17.7,10.1,19.8,24.4,16.0,33.0,3318.0,2453.0,1999-2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,3136.0,56.0,37.0,Sweetwater,Wyoming,WY,77.0,8.8,4.0,5.6,...,13.6,28.1,20.4,37.3,29.5,23.0,45.0,2756.0,1264.0,1999-2003
3137,3137.0,56.0,39.0,Teton,Wyoming,WY,78.0,8.0,4.0,3.1,...,0.0,29.5,7.6,21.0,26.9,6.0,63.0,1931.0,680.0,1994-2003
3138,3138.0,56.0,41.0,Uinta,Wyoming,WY,38.0,11.4,4.0,5.5,...,7.5,20.3,12.5,26.1,25.5,15.0,28.0,3186.0,1060.0,1994-2003
3139,3139.0,56.0,43.0,Washakie,Wyoming,WY,82.0,7.3,4.0,2.5,...,6.1,26.4,7.2,24.7,33.3,11.0,36.0,974.0,844.0,1994-2003
3140,3140.0,56.0,45.0,Weston,Wyoming,WY,78.0,8.8,4.0,3.1,...,0.0,29.5,7.5,29.3,22.6,6.0,63.0,670.0,629.0,1994-2003

In [24]:
# Renaming the columns
df.rename(columns={'LBW':'Low_Birth_weight'},inplace=True)
df

,index,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,Low_Birth_weight,LBW_Ind,Min_LBW,...,Min_Suicide,Max_Suicide,CI_Min_Suicide,CI_Max_Suicide,Injury,Min_Injury,Max_Injury,Total_Births,Total_Deaths,MOBD_Time_Span
0,0.0,1.0,1.0,Autauga,Alabama,AL,29.0,8.1,4.0,6.0,...,6.7,14.5,11.7,23.0,23.0,16.0,28.0,3048.0,1867.0,1999-2003
1,1.0,1.0,3.0,Baldwin,Alabama,AL,16.0,8.6,4.0,6.3,...,7.7,16.0,11.0,18.2,30.1,16.0,29.0,5471.0,4388.0,2001-2003
2,2.0,1.0,5.0,Barbour,Alabama,AL,51.0,11.0,4.0,6.7,...,6.1,17.6,5.7,16.9,29.6,18.0,35.0,1835.0,1538.0,1999-2003
3,3.0,1.0,7.0,Bibb,Alabama,AL,42.0,8.7,4.0,5.1,...,8.5,21.6,9.9,21.3,30.0,20.0,38.0,2801.0,2012.0,1994-2003
4,4.0,1.0,9.0,Blount,Alabama,AL,28.0,7.6,4.0,5.2,...,8.5,17.7,10.1,19.8,24.4,16.0,33.0,3318.0,2453.0,1999-2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,3136.0,56.0,37.0,Sweetwater,Wyoming,WY,77.0,8.8,4.0,5.6,...,13.6,28.1,20.4,37.3,29.5,23.0,45.0,2756.0,1264.0,1999-2003
3137,3137.0,56.0,39.0,Teton,Wyoming,WY,78.0,8.0,4.0,3.1,...,0.0,29.5,7.6,21.0,26.9,6.0,63.0,1931.0,680.0,1994-2003
3138,3138.0,56.0,41.0,Uinta,Wyoming,WY,38.0,11.4,4.0,5.5,...,7.5,20.3,12.5,26.1,25.5,15.0,28.0,3186.0,1060.0,1994-2003
3139,3139.0,56.0,43.0,Washakie,Wyoming,WY,82.0,7.3,4.0,2.5,...,6.1,26.4,7.2,24.7,33.3,11.0,36.0,974.0,844.0,1994-2003
3140,3140.0,56.0,45.0,Weston,Wyoming,WY,78.0,8.8,4.0,3.1,...,0.0,29.5,7.5,29.3,22.6,6.0,63.0,670.0,629.0,1994-2003

In [25]:
# Calculated field creation
df['Min_Injury'] = pd.to_numeric(df['Min_Injury'], errors='coerce')
df['Max_Injury'] = pd.to_numeric(df['Max_Injury'], errors='coerce')
df['Avg_Injury'] = (df['Min_Injury'] + df['Max_Injury']) / 2
df

,index,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,Low_Birth_weight,LBW_Ind,Min_LBW,...,Max_Suicide,CI_Min_Suicide,CI_Max_Suicide,Injury,Min_Injury,Max_Injury,Total_Births,Total_Deaths,MOBD_Time_Span,Avg_Injury
0,0.0,1.0,1.0,Autauga,Alabama,AL,29.0,8.1,4.0,6.0,...,14.5,11.7,23.0,23.0,16.0,28.0,3048.0,1867.0,1999-2003,22.0
1,1.0,1.0,3.0,Baldwin,Alabama,AL,16.0,8.6,4.0,6.3,...,16.0,11.0,18.2,30.1,16.0,29.0,5471.0,4388.0,2001-2003,22.5
2,2.0,1.0,5.0,Barbour,Alabama,AL,51.0,11.0,4.0,6.7,...,17.6,5.7,16.9,29.6,18.0,35.0,1835.0,1538.0,1999-2003,26.5
3,3.0,1.0,7.0,Bibb,Alabama,AL,42.0,8.7,4.0,5.1,...,21.6,9.9,21.3,30.0,20.0,38.0,2801.0,2012.0,1994-2003,29.0
4,4.0,1.0,9.0,Blount,Alabama,AL,28.0,7.6,4.0,5.2,...,17.7,10.1,19.8,24.4,16.0,33.0,3318.0,2453.0,1999-2003,24.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,3136.0,56.0,37.0,Sweetwater,Wyoming,WY,77.0,8.8,4.0,5.6,...,28.1,20.4,37.3,29.5,23.0,45.0,2756.0,1264.0,1999-2003,34.0
3137,3137.0,56.0,39.0,Teton,Wyoming,WY,78.0,8.0,4.0,3.1,...,29.5,7.6,21.0,26.9,6.0,63.0,1931.0,680.0,1994-2003,34.5
3138,3138.0,56.0,41.0,Uinta,Wyoming,WY,38.0,11.4,4.0,5.5,...,20.3,12.5,26.1,25.5,15.0,28.0,3186.0,1060.0,1994-2003,21.5
3139,3139.0,56.0,43.0,Washakie,Wyoming,WY,82.0,7.3,4.0,2.5,...,26.4,7.2,24.7,33.3,11.0,36.0,974.0,844.0,1994-2003,23.5
3140,3140.0,56.0,45.0,Weston,Wyoming,WY,78.0,8.8,4.0,3.1,...,29.5,7.5,29.3,22.6,6.0,63.0,670.0,629.0,1994-2003,34.5

In [33]:
# DROPPING DUPLICATE ROWS:
df.drop_duplicates()
df

,index,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,Low_Birth_weight,LBW_Ind,Min_LBW,...,Max_Suicide,CI_Min_Suicide,CI_Max_Suicide,Injury,Min_Injury,Max_Injury,Total_Births,Total_Deaths,MOBD_Time_Span,Avg_Injury
0,0.0,1.0,1.0,Autauga,Alabama,AL,29.0,8.1,4.0,6.0,...,14.5,11.7,23.0,23.0,16.0,28.0,3048.0,1867.0,1999-2003,22.0
1,1.0,1.0,3.0,Baldwin,Alabama,AL,16.0,8.6,4.0,6.3,...,16.0,11.0,18.2,30.1,16.0,29.0,5471.0,4388.0,2001-2003,22.5
2,2.0,1.0,5.0,Barbour,Alabama,AL,51.0,11.0,4.0,6.7,...,17.6,5.7,16.9,29.6,18.0,35.0,1835.0,1538.0,1999-2003,26.5
3,3.0,1.0,7.0,Bibb,Alabama,AL,42.0,8.7,4.0,5.1,...,21.6,9.9,21.3,30.0,20.0,38.0,2801.0,2012.0,1994-2003,29.0
4,4.0,1.0,9.0,Blount,Alabama,AL,28.0,7.6,4.0,5.2,...,17.7,10.1,19.8,24.4,16.0,33.0,3318.0,2453.0,1999-2003,24.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,3136.0,56.0,37.0,Sweetwater,Wyoming,WY,77.0,8.8,4.0,5.6,...,28.1,20.4,37.3,29.5,23.0,45.0,2756.0,1264.0,1999-2003,34.0
3137,3137.0,56.0,39.0,Teton,Wyoming,WY,78.0,8.0,4.0,3.1,...,29.5,7.6,21.0,26.9,6.0,63.0,1931.0,680.0,1994-2003,34.5
3138,3138.0,56.0,41.0,Uinta,Wyoming,WY,38.0,11.4,4.0,5.5,...,20.3,12.5,26.1,25.5,15.0,28.0,3186.0,1060.0,1994-2003,21.5
3139,3139.0,56.0,43.0,Washakie,Wyoming,WY,82.0,7.3,4.0,2.5,...,26.4,7.2,24.7,33.3,11.0,36.0,974.0,844.0,1994-2003,23.5
3140,3140.0,56.0,45.0,Weston,Wyoming,WY,78.0,8.8,4.0,3.1,...,29.5,7.5,29.3,22.6,6.0,63.0,670.0,629.0,1994-2003,34.5